-- onis.ro
-- 10 September 2013
-- use this to import list of countries with alpha2, alpha3, numeric sorted by continents
-- http://en.wikipedia.org/wiki/ISO_3166-1
-- http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

CREATE TABLE IF NOT EXISTS `onis_countries` (
`id` int(11) NOT NULL auto_increment,
`name` varchar(100) NOT NULL default '',
`alpha-2` varchar(2) NOT NULL default '0',
`alpha-3` varchar(3) NOT NULL default '0',
`numeric` varchar(3) NOT NULL default '0',
`continent` tinyint(1) NOT NULL default '0',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 
-- Dumping data for table `countries`
-- 
INSERT INTO `onis_countries` (`name`, `alpha-2`, `alpha-3`, `numeric`, `continent`) VALUES
('Afghanistan', 'AF', 'AFG', '004', '3'),
('Åland Islands', 'AX', 'ALA', '248', '4'),
('Albania', 'AL', 'ALB', '008', '4'),
('Algeria', 'DZ', 'DZA', '012', '1'),
('American Samoa', '3', 'ASM', '016', '6'),
('Andorra', 'AD', 'AND', '020', '4'),
('Angola', 'AO', 'AGO', '024', '1'),
('Anguilla', 'AI', 'AIA', '660', '5'),
('Antarctica', 'AQ', 'ATA', '010', '2'),
('Antigua and Barbuda', 'AG', 'ATG', '028', '5'),
('Argentina', 'AR', 'ARG', '032', '7'),
('Armenia', 'AM', 'ARM', '051', '3'),
('Aruba', 'AW', 'ABW', '533', '5'),
('Australia', 'AU', 'AUS', '036', '6'),
('Austria', 'AT', 'AUT', '040', '4'),
('Azerbaijan', 'AZ', 'AZE', '031', '3'),
('Bahamas', 'BS', 'BHS', '044', '5'),
('Bahrain', 'BH', 'BHR', '048', '3'),
('Bangladesh', 'BD', 'BGD', '050', '3'),
('Barbados', 'BB', 'BRB', '052', '5'),
('Belarus', 'BY', 'BLR', '112', '4'),
('Belgium', 'BE', 'BEL', '056', '4'),
('Belize', 'BZ', 'BLZ', '084', '5'),
('Benin', 'BJ', 'BEN', '204', '1'),
('Bermuda', 'BM', 'BMU', '060', '5'),
('Bhutan', 'BT', 'BTN', '064', '3'),
('Bolivia', 'BO', 'BOL', '068', '7'),
('Bonaire', 'BQ', 'BES', '535', '5'),
('Bosnia and Herzegovina', 'BA', 'BIH', '070', '4'),
('Botswana', 'BW', 'BWA', '072', '1'),
('Bouvet Island', 'BV', 'BVT', '074', '2'),
('Brazil', 'BR', 'BRA', '076', '7'),
('British Indian Ocean Territory', 'IO', 'IOT', '086', '3'),
('Brunei Darussalam', 'BN', 'BRN', '096', '3'),
('Bulgaria', 'BG', 'BGR', '100', '4'),
('Burkina Faso', 'BF', 'BFA', '854', '1'),
('Burundi', 'BI', 'BDI', '108', '1'),
('Cambodia', 'KH', 'KHM', '116', '3'),
('Cameroon', 'CM', 'CMR', '120', '1'),
('Canada', 'CA', 'CAN', '124', '5'),
('Cape Verde', 'CV', 'CPV', '132', '1'),
('Cayman Islands', 'KY', 'CYM', '136', '5'),
('Central African Republic', 'CF', 'CAF', '140', '1'),
('Chad', 'TD', 'TCD', '148', '1'),
('Chile', 'CL', 'CHL', '152', '7'),
('China', 'CN', 'CHN', '156', '3'),
('Christmas Island', 'CX', 'CXR', '162', '3'),
('Cocos (Keeling) Islands', 'CC', 'CCK', '166', '3'),
('Colombia', 'CO', 'COL', '170', '7'),
('Comoros', 'KM', 'COM', '174', '1'),
('Congo', 'CG', 'COG', '178', '1'),
('Congo, the Democratic Republic of the', 'CD', 'COD', '180', '1'),
('Cook Islands', 'CK', 'COK', '184', '6'),
('Costa Rica', 'CR', 'CRI', '188', '5'),
('C%C3%B4te_d%27Ivoire', 'CI', 'CIV', '384', '1'),
('Croatia', 'HR', 'HRV', '191', '4'),
('Cuba', 'CU', 'CUB', '192', '5'),
('Curaçao', 'CW', 'CUW', '531', '5'),
('Cyprus', 'CY', 'CYP', '196', '3'),
('Czech Republic', 'CZ', 'CZE', '203', '4'),
('Denmark', 'DK', 'DNK', '208', '4'),
('Djibouti', 'DJ', 'DJI', '262', '1'),
('Dominica', 'DM', 'DMA', '212', '5'),
('Dominican Republic', 'DO', 'DOM', '214', '5'),
('Ecuador', 'EC', 'ECU', '218', '7'),
('Egypt', 'EG', 'EGY', '818', '1'),
('El Salvador', 'SV', 'SLV', '222', '5'),
('Equatorial Guinea', 'GQ', 'GNQ', '226', '1'),
('Eritrea', 'ER', 'ERI', '232', '1'),
('Estonia', 'EE', 'EST', '233', '4'),
('Ethiopia', 'ET', 'ETH', '231', '1'),
('Falkland Islands', 'FK', 'FLK', '238', '7'),
('Faroe Islands', 'FO', 'FRO', '234', '4'),
('Fiji', 'FJ', 'FJI', '242', '6'),
('Finland', 'FI', 'FIN', '246', '4'),
('France', 'FR', 'FRA', '250', '4'),
('French Guiana', 'GF', 'GUF', '254', '7'),
('French Polynesia', 'PF', 'PYF', '258', '6'),
('French Southern Territories', 'TF', 'ATF', '260', '2'),
('Gabon', 'GA', 'GAB', '266', '1'),
('Gambia', 'GM', 'GMB', '270', '1'),
('Georgia', 'GE', 'GEO', '268', '3'),
('Germany', 'DE', 'DEU', '276', '4'),
('Ghana', 'GH', 'GHA', '288', '1'),
('Gibraltar', 'GI', 'GIB', '292', '4'),
('Greece', 'GR', 'GRC', '300', '4'),
('Greenland', 'GL', 'GRL', '304', '5'),
('Grenada', 'GD', 'GRD', '308', '5'),
('Guadeloupe', 'GP', 'GLP', '312', '5'),
('Guam', 'GU', 'GUM', '316', '6'),
('Guatemala', 'GT', 'GTM', '320', '5'),
('Guernsey', 'GG', 'GGY', '831', '4'),
('Guinea', 'GN', 'GIN', '324', '1'),
('Guinea-Bissau', 'GW', 'GNB', '624', '1'),
('Guyana', 'GY', 'GUY', '328', '7'),
('Haiti', 'HT', 'HTI', '332', '5'),
('Heard Island and McDonald Islands', 'HM', 'HMD', '334', '2'),
('Honduras', 'HN', 'HND', '340', '5'),
('Hong Kong', 'HK', 'HKG', '344', '3'),
('Hungary', 'HU', 'HUN', '348', '4'),
('Iceland', 'IS', 'ISL', '352', '4'),
('India', 'IN', 'IND', '356', '3'),
('Indonesia', 'ID', 'IDN', '360', '3'),
('Iran', 'IR', 'IRN', '364', '3'),
('Iraq', 'IQ', 'IRQ', '368', '3'),
('Ireland', 'IE', 'IRL', '372', '4'),
('Isle of Man', 'IM', 'IMN', '833', '4'),
('Israel', 'IL', 'ISR', '376', '3'),
('Italy', 'IT', 'ITA', '380', '4'),
('Jamaica', 'JM', 'JAM', '388', '5'),
('Japan', 'JP', 'JPN', '392', '3'),
('Jersey', 'JE', 'JEY', '832', '4'),
('Jordan', 'JO', 'JOR', '400', '3'),
('Kazakhstan', 'KZ', 'KAZ', '398', '3'),
('Kenya', 'KE', 'KEN', '404', '1'),
('Kiribati', 'KI', 'KIR', '296', '6'),
('Kuwait', 'KW', 'KWT', '414', '3'),
('Kyrgyzstan', 'KG', 'KGZ', '417', '3'),
('Laos', 'LA', 'LAO', '418', '3'),
('Latvia', 'LV', 'LVA', '428', '4'),
('Lebanon', 'LB', 'LBN', '422', '3'),
('Lesotho', 'LS', 'LSO', '426', '1'),
('Liberia', 'LR', 'LBR', '430', '1'),
('Libya', 'LY', 'LBY', '434', '1'),
('Liechtenstein', 'LI', 'LIE', '438', '4'),
('Lithuania', 'LT', 'LTU', '440', '4'),
('Luxembourg', 'LU', 'LUX', '442', '4'),
('MacaO', 'MO', 'MAC', '446', '3'),
('Macedonia', 'MK', 'MKD', '807', '4'),
('Madagascar', 'MG', 'MDG', '450', '1'),
('Malawi', 'MW', 'MWI', '454', '1'),
('Malaysia', 'MY', 'MYS', '458', '3'),
('Maldives', 'MV', 'MDV', '462', '3'),
('Mali', 'ML', 'MLI', '466', '1'),
('Malta', 'MT', 'MLT', '470', '4'),
('Marshall Islands', 'MH', 'MHL', '584', '6'),
('Martinique', 'MQ', 'MTQ', '474', '5'),
('Mauritania', 'MR', 'MRT', '478', '1'),
('Mauritius', 'MU', 'MUS', '480', '1'),
('Mayotte', 'YT', 'MYT', '175', '1'),
('Mexico', 'MX', 'MEX', '484', '5'),
('Micronesia', 'FM', 'FSM', '583', '6'),
('Moldova', 'MD', 'MDA', '498', '4'),
('Monaco', 'MC', 'MCO', '492', '4'),
('Mongolia', 'MN', 'MNG', '496', '3'),
('Montenegro', 'ME', 'MNE', '499', '4'),
('Montserrat', 'MS', 'MSR', '500', '5'),
('Morocco', 'MA', 'MAR', '504', '1'),
('Mozambique', 'MZ', 'MOZ', '508', '1'),
('Myanmar', 'MM', 'MMR', '104', '3'),
('Namibia', '5', 'NAM', '516', '1'),
('Nauru', 'NR', 'NRU', '520', '6'),
('Nepal', 'NP', 'NPL', '524', '3'),
('Netherlands', 'NL', 'NLD', '528', '4'),
('New Caledonia', 'NC', 'NCL', '540', '6'),
('New Zealand', 'NZ', 'NZL', '554', '6'),
('Nicaragua', 'NI', 'NIC', '558', '5'),
('Niger', 'NE', 'NER', '562', '1'),
('Nigeria', 'NG', 'NGA', '566', '1'),
('Niue', 'NU', 'NIU', '570', '6'),
('Norfolk Island', 'NF', 'NFK', '574', '6'),
('North Korea', 'KP', 'PRK', '408', '3'),
('Northern Mariana Islands', 'MP', 'MNP', '580', '6'),
('Norway', 'NO', 'NOR', '578', '4'),
('Oman', 'OM', 'OMN', '512', '3'),
('Pakistan', 'PK', 'PAK', '586', '3'),
('Palau', 'PW', 'PLW', '585', '6'),
('Palestine', 'PS', 'PSE', '275', '3'),
('Panama', 'PA', 'PAN', '591', '5'),
('Papua New Guinea', 'PG', 'PNG', '598', '6'),
('Paraguay', 'PY', 'PRY', '600', '7'),
('Peru', 'PE', 'PER', '604', '7'),
('Philippines', 'PH', 'PHL', '608', '3'),
('Pitcairn', 'PN', 'PCN', '612', '6'),
('Poland', 'PL', 'POL', '616', '4'),
('Portugal', 'PT', 'PRT', '620', '4'),
('Puerto Rico', 'PR', 'PRI', '630', '5'),
('Qatar', 'QA', 'QAT', '634', '3'),
('Réunion', 'RE', 'REU', '638', '1'),
('Romania', 'RO', 'ROU', '642', '4'),
('Russia', 'RU', 'RUS', '643', '4'),
('Rwanda', 'RW', 'RWA', '646', '1'),
('Saint Barthélemy', 'BL', 'BLM', '652', '5'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654', '1'),
('Saint Kitts and Nevis', 'KN', 'KNA', '659', '5'),
('Saint Lucia', 'LC', 'LCA', '662', '5'),
('Saint Martin (French part)', 'MF', 'MAF', '663', '5'),
('Saint Pierre and Miquelon', 'PM', 'SPM', '666', '5'),
('Saint Vincent and the Grenadines', 'VC', 'VCT', '670', '5'),
('Samoa', 'WS', 'WSM', '882', '6'),
('San Marino', 'SM', 'SMR', '674', '4'),
('Sao Tome and Principe', 'ST', 'STP', '678', '1'),
('Saudi Arabia', '7', 'SAU', '682', '3'),
('Senegal', 'SN', 'SEN', '686', 'F'),
('Serbia', 'RS', 'SRB', '688', '4'),
('Seychelles', 'SC', 'SYC', '690', '1'),
('Sierra Leone', 'SL', 'SLE', '694', '1'),
('Singapore', 'SG', 'SGP', '702', '3'),
('Sint Maarten', 'SX', 'SXM', '534', '5'),
('Slovakia', 'SK', 'SVK', '703', '4'),
('Slovenia', 'SI', 'SVN', '705', '4'),
('Solomon Islands', 'SB', 'SLB', '090', '6'),
('Somalia', 'SO', 'SOM', '706', '1'),
('South Africa', 'ZA', 'ZAF', '710', '1'),
('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', '2'),
('South Korea', 'KR', 'KOR', '410', '3'),
('South Sudan', 'SS', 'SSD', '728', '1'),
('Spain', 'ES', 'ESP', '724', '4'),
('Sri Lanka', 'LK', 'LKA', '144', '3'),
('Sudan', 'SD', 'SDN', '729', '1'),
('Suriname', 'SR', 'SUR', '740', '7'),
('Svalbard', 'SJ', 'SJM', '744', '4'),
('Swaziland', 'SZ', 'SWZ', '748', '1'),
('Sweden', 'SE', 'SWE', '752', '4'),
('Switzerland', 'CH', 'CHE', '756', '4'),
('Syria', 'SY', 'SYR', '760', '3'),
('Taiwan', 'TW', 'TWN', '158', '3'),
('Tajikistan', 'TJ', 'TJK', '762', '3'),
('Tanzania', 'TZ', 'TZA', '834', '1'),
('Thailand', 'TH', 'THA', '764', '3'),
('Timor-Leste', 'TL', 'TLS', '626', '3'),
('Togo', 'TG', 'TGO', '768', '1'),
('Tokelau', 'TK', 'TKL', '772', '6'),
('Tonga', 'TO', 'TON', '776', '6'),
('Trinidad and Tobago', 'TT', 'TTO', '780', '5'),
('Tunisia', 'TN', 'TUN', '788', '1'),
('Turkey', 'TR', 'TUR', '792', '3'),
('Turkmenistan', 'TM', 'TKM', '795', '3'),
('Turks and Caicos Islands', 'TC', 'TCA', '796', '5'),
('Tuvalu', 'TV', 'TUV', '798', '6'),
('Uganda', 'UG', 'UGA', '800', '1'),
('Ukraine', 'UA', 'UKR', '804', '4'),
('United Arab Emirates', 'AE', 'ARE', '784', '3'),
('United Kingdom', 'GB', 'GBR', '826', '4'),
('United States', 'US', 'USA', '840', '5'),
('United States Minor Outlying Islands', 'UM', 'UMI', '581', '5'),
('Uruguay', 'UY', 'URY', '858', '7'),
('Uzbekistan', 'UZ', 'UZB', '860', '3'),
('Vanuatu', 'VU', 'VUT', '548', '6'),
('Vatican City', 'VA', 'VAT', '336', '4'),
('Venezuela, Bolivarian Republic of', 'VE', 'VEN', '862', '7'),
('Vietnam', 'VN', 'VNM', '704', '3'),
('Virgin Islands, British', 'VG', 'VGB', '092', '5'),
('Virgin Islands, U.S.', 'VI', 'VIR', '850', '5'),
('Wallis and Futuna', 'WF', 'WLF', '876', '6'),
('Western Sahara', 'EH', 'ESH', '732', '1'),
('Yemen', 'YE', 'YEM', '887', '3'),
('Zambia', 'ZM', 'ZMB', '894', '1'),
('Zimbabwe', 'ZW', 'ZWE', '716', '1');
